[package]
name = "tsnet-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
bundled = []

[dependencies]

[build-dependencies]
bindgen = "0.53.1"
